name: Feature Request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us by suggesting a feature!
        Please verify that a similar feature has not been suggested before through the issue tracker.
  - type: textarea
    id: description
    attributes:
      label: Motivation and description
      description: Explain why the suggested feature is needed and give a detailed description.
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: If possible, add a possible implementation for the suggested feature.
      placeholder: |
        X can be implemented by referring to the Y paper or the Z blog post.
        I have implemented X locally using the following code -
        ...
